### ISSUE TITLE
3phase_integrated License?

### ISSUE THREAD

**Issue by JoeyByrnes** [bgkatz/3phase_integrated#4]
Hi Ben, 
Love your work. I noticed there's no license file in this repository. Are these files released under an open source license? If so could you let me know what license and where it's documented if anywhere? I'm wondering if I'm permitted to use any of your work in a future OpenLeg Drive. (same question applies to your mbed repositories)

Thanks,
Joey Byrnes

**Comment by bgkatz** [comment]
Fixed, added MIT License

**Comment by bgkatz** [comment]
The mbed repository is also under the MIT License (see bottom right corner of the page):
https://os.mbed.com/users/benkatz/code/HKC_MiniCheetah/

**Comment by JoeyByrnes** [comment]
Wow you work fast, Thanks!
